name: Jest
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install modules
        run: |
          cd app/client
          yarn
      
      - name: Test & publish coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn run test --coverage
          workingDirectory: app/client